In [1]:
#using baynesian search for hyperparameter tuning

In [2]:
#learning optuna for bynesian

In [3]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 7.7 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [4]:
#using indian diabetes dataset

In [5]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

df = pd.read_csv(url, names = columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
import numpy as np

#Replace zero values with NaN in columns where zero is not a valid value
cols_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_missing_vals] = df[cols_missing_vals].replace(0, np.nan)

#Impute missing values with mean of respective column
df.fillna(df.mean(), inplace = True)

#Checking for remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
X = df.drop('Outcome', axis = 1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

scaler = StandardScaler()
X_train  = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f'Training set shape:{X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape:(537, 8)
Test set shape: (231, 8)

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#Defining objective function
def objective(trial):
  #Suggestive hyperparameters with values
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  #Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators = n_estimators,
      max_depth = max_depth,
      random_state = 42
  )

  #Perform 3 fold cross validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv = 3, scoring = 'accuracy').mean()
  #returning the accuracy score for optuna to optimize
  return score

In [31]:
#Create a study object and optimize the objective function
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.TPESampler())
#creating 50 trials to find best hyperparameters
study.optimize(objective, n_trials = 50)

[I 2026-04-24 13:08:25,241] A new study created in memory with name: no-name-612d2b58-4b32-4bb6-a01b-6c5221ef64d5
[I 2026-04-24 13:08:26,058] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:26,648] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 96, 'max_depth': 17}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:27,483] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:28,553] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 180, 'max_depth': 8}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:29,005] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 72, 'max_depth': 6}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:30,015] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 151, 'max_depth': 6}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:31,351] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:32,654] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 186, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-04-24 13:08:33,880] Trial 8 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 197, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:34,584] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 112, 'max_depth': 11}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:35,966] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 160, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:37,402] Trial 11 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:37,949] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 56, 'max_depth': 15}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:38,992] Trial 13 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 102, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:40,113] Trial 14 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 165, 'max_depth': 3}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:41,383] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 14}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:41,964] Trial 16 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 84, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491619.
[I 2026-04-24 13:08:42,847] Trial 17 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 18}. Best is trial 17 with value: 0.7783985102420856.
[I 2026-04-24 13:08:43,573] Trial 18 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 18}. Best is trial 17 with value: 0.7783985102420856.
[I 2026-04-24 13:08:44,339] Trial 19 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 17 with value: 0.7783985102420856.
[I 2026-04-24 13:08:45,009] Trial 20 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 105, 'max_depth': 18}. Best is trial 17 with value: 0.7783985102420856.
[I 2026-04-24 13:08:45,754] Trial 21 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 119, 'max_depth': 19}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:46,520] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 120, 'max_depth': 16}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:47,111] Trial 23 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 20}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:48,021] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:48,523] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 79, 'max_depth': 15}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:49,255] Trial 26 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:50,388] Trial 27 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:51,695] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 133, 'max_depth': 9}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:52,985] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 13}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:54,346] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 151, 'max_depth': 16}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:55,083] Trial 31 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 115, 'max_depth': 19}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:55,703] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 99, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:56,506] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 127, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:57,329] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:58,196] Trial 35 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:08:59,100] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 15}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:00,164] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 167, 'max_depth': 12}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:01,160] Trial 38 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 154, 'max_depth': 19}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:01,973] Trial 39 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:02,671] Trial 40 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 9}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:03,571] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:04,736] Trial 42 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 17}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:05,950] Trial 43 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 128, 'max_depth': 16}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:07,463] Trial 44 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 145, 'max_depth': 14}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:08,741] Trial 45 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 16}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:09,637] Trial 46 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 138, 'max_depth': 16}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:10,611] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 20}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:11,215] Trial 48 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 12}. Best is trial 21 with value: 0.7821229050279329.
[I 2026-04-24 13:09:12,143] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 15}. Best is trial 21 with value: 0.7821229050279329.

In [32]:
print(f"Best trial accuracy: {study.best_trial.value}")
print(f"Best Hyperparameters: {study.best_trial.params}")

Best trial accuracy: 0.7821229050279329
Best Hyperparameters: {'n_estimators': 119, 'max_depth': 19}

In [33]:
from sklearn.metrics import accuracy_score

#training RandomForestClassifier using the best hyperparameter from optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state = 42)

#Fit the model to the training data
best_model.fit(X_train, y_train)

#Make predictions on the test set
y_pred = best_model.predict(X_test)

#Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

In [34]:
print(f"Test Accuracy with best hyperparameters: {test_accuracy:.2f}")

Test Accuracy with best hyperparameters: 0.74

In [17]:
#using randomizedSearch for hyperparameters

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#Defining objective function
def objective(trial):
  #Suggestive hyperparameters with values
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  #Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators = n_estimators,
      max_depth = max_depth,
      random_state = 42
  )

  #Perform 3 fold cross validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv = 3, scoring = 'accuracy').mean()
  #returning the accuracy score for optuna to optimize
  return score

In [19]:
#Create a study object and optimize the objective function
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.RandomSampler())
#creating 50 trials to find best hyperparameters
study.optimize(objective, n_trials = 50)

[I 2026-04-24 12:57:18,572] A new study created in memory with name: no-name-9715ec26-148b-4956-ae49-1677b55952dd
[I 2026-04-24 12:57:19,028] Trial 0 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 0 with value: 0.7672253258845437.
[I 2026-04-24 12:57:19,525] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 69, 'max_depth': 8}. Best is trial 1 with value: 0.7709497206703911.
[I 2026-04-24 12:57:20,561] Trial 2 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 169, 'max_depth': 7}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:21,162] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 94, 'max_depth': 11}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:21,829] Trial 4 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 71, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:23,336] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 167, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:24,606] Trial 6 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 134, 'max_depth': 15}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:25,627] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 104, 'max_depth': 16}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:26,130] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 81, 'max_depth': 4}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:27,104] Trial 9 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 177, 'max_depth': 3}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:27,498] Trial 10 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 60, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:28,675] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 186, 'max_depth': 20}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:29,032] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 52, 'max_depth': 14}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:29,495] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 64, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:29,877] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 17}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:30,341] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 73, 'max_depth': 7}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:31,369] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 163, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:31,915] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 84, 'max_depth': 12}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:32,496] Trial 18 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 9}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:33,085] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 85, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:33,590] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 75, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:34,466] Trial 21 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 146, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:35,594] Trial 22 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 179, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:36,537] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 18}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:38,299] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 185, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:39,626] Trial 25 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 148, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:40,733] Trial 26 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:41,895] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 15}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:42,279] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 51, 'max_depth': 15}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:43,453] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 198, 'max_depth': 5}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:44,073] Trial 30 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 97, 'max_depth': 6}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:44,851] Trial 31 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 131, 'max_depth': 5}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:46,012] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 196, 'max_depth': 7}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:46,494] Trial 33 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 83, 'max_depth': 4}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:47,723] Trial 34 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 193, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:48,298] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 89, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:48,825] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 75, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:50,094] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 195, 'max_depth': 13}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:51,004] Trial 38 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 95, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:53,316] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-04-24 12:57:54,838] Trial 40 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 20}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:57:57,007] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 175, 'max_depth': 18}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:57:57,689] Trial 42 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 75, 'max_depth': 4}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:57:58,806] Trial 43 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 135, 'max_depth': 6}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:57:59,803] Trial 44 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 172, 'max_depth': 4}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:58:00,588] Trial 45 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 114, 'max_depth': 15}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:58:01,198] Trial 46 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 98, 'max_depth': 9}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:58:02,096] Trial 47 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 155, 'max_depth': 3}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:58:02,649] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 78, 'max_depth': 13}. Best is trial 40 with value: 0.7765363128491621.
[I 2026-04-24 12:58:03,949] Trial 49 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 14}. Best is trial 40 with value: 0.7765363128491621.

In [20]:
print(f"Best trial accuracy: {study.best_trial.value}")
print(f"Best Hyperparameters: {study.best_trial.params}")

Best trial accuracy: 0.7765363128491621
Best Hyperparameters: {'n_estimators': 114, 'max_depth': 20}

In [21]:
from sklearn.metrics import accuracy_score

#training RandomForestClassifier using the best hyperparameter from optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state = 42)

#Fit the model to the training data
best_model.fit(X_train, y_train)

#Make predictions on the test set
y_pred = best_model.predict(X_test)

#Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

print(f"Test Accuracy with best hyperparameters: {test_accuracy:.2f}")

Test Accuracy with best hyperparameters: 0.75

In [22]:
#using gridsearchCV for hyperparameter tuning

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#Defining objective function
def objective(trial):
  #Suggestive hyperparameters with values
  n_estimators = trial.suggest_int('n_estimators', 50, 200)
  max_depth = trial.suggest_int('max_depth', 3, 20)

  #Create the RandomForestClassifier with suggested hyperparameters
  model = RandomForestClassifier(
      n_estimators = n_estimators,
      max_depth = max_depth,
      random_state = 42
  )

  #Perform 3 fold cross validation and calculate accuracy
  score = cross_val_score(model, X_train, y_train, cv = 3, scoring = 'accuracy').mean()
  #returning the accuracy score for optuna to optimize
  return score

In [24]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth' : [5, 10, 15, 20]
}

In [25]:
#Create a study object and optimize the objective function
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.RandomSampler())
#creating 50 trials to find best hyperparameters
study.optimize(objective, n_trials = 50)

[I 2026-04-24 13:00:35,788] A new study created in memory with name: no-name-8340bd61-7d79-401a-b487-c8b8078dccdc
[I 2026-04-24 13:00:36,644] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 6}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-04-24 13:00:37,393] Trial 1 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 7}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:38,403] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 150, 'max_depth': 16}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:39,497] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 142, 'max_depth': 11}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:40,437] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 135, 'max_depth': 11}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:40,963] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:41,408] Trial 6 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 59, 'max_depth': 19}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:42,602] Trial 7 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 140, 'max_depth': 14}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:44,640] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 14}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:46,402] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 177, 'max_depth': 11}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:47,883] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 11}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:48,473] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 87, 'max_depth': 17}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:48,986] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 19}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:49,625] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 79, 'max_depth': 8}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:50,922] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 192, 'max_depth': 13}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:51,266] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 52, 'max_depth': 15}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:52,144] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 7}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:52,885] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 116, 'max_depth': 10}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:53,962] Trial 18 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 188, 'max_depth': 3}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:55,189] Trial 19 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 180, 'max_depth': 12}. Best is trial 1 with value: 0.7746741154562384.
[I 2026-04-24 13:00:55,981] Trial 20 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:00:56,621] Trial 21 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 81, 'max_depth': 7}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:00:57,485] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 16}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:00:58,536] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 129, 'max_depth': 5}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:00,404] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 183, 'max_depth': 10}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:01,418] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 110, 'max_depth': 7}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:02,223] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 77, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:02,851] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 73, 'max_depth': 7}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:04,171] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 191, 'max_depth': 15}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:05,175] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 154, 'max_depth': 10}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:06,474] Trial 30 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 175, 'max_depth': 10}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:07,045] Trial 31 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 75, 'max_depth': 13}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:07,886] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 112, 'max_depth': 15}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:08,532] Trial 33 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 86, 'max_depth': 18}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:09,144] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 15}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:09,787] Trial 35 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 82, 'max_depth': 10}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:11,129] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 199, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:12,874] Trial 37 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 89, 'max_depth': 18}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:15,557] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 164, 'max_depth': 9}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:17,668] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 135, 'max_depth': 8}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:20,082] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 162, 'max_depth': 18}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:21,213] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:22,544] Trial 42 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 178, 'max_depth': 3}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:23,128] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 66, 'max_depth': 10}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:23,800] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 74, 'max_depth': 4}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:24,662] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 54, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:26,526] Trial 46 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 191, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:27,525] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 156, 'max_depth': 11}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:28,563] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 18}. Best is trial 20 with value: 0.7765363128491621.
[I 2026-04-24 13:01:29,628] Trial 49 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 169, 'max_depth': 4}. Best is trial 20 with value: 0.7765363128491621.

In [ ]:
print(f"Best trial accuracy: {study.best_trial.value}")
print(f"Best Hyperparameters: {study.best_trial.params}")

In [26]:
from sklearn.metrics import accuracy_score

#training RandomForestClassifier using the best hyperparameter from optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state = 42)

#Fit the model to the training data
best_model.fit(X_train, y_train)

#Make predictions on the test set
y_pred = best_model.predict(X_test)

#Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

print(f"Test Accuracy with best hyperparameters: {test_accuracy:.2f}")

Test Accuracy with best hyperparameters: 0.75

Visulazation in optuna

In [27]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [37]:
plot_optimization_history(study).show()

In [38]:
plot_parallel_coordinate(study).show()

In [35]:
plot_slice(study).show()

In [36]:
plot_contour(study).show()

In [39]:
plot_param_importances(study).show()

In [40]:
#optimizing multiple ml models

In [41]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [44]:
def objective(trial):
  classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

  if classifier_name == 'SVM':
    c = trial.suggest_float('C', 0.1, 100, log = True)
    kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])
    model = SVC(C=c, kernel=kernel, gamma = gamma,  random_state=42)

  elif classifier_name == 'RandomForest':
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])

    model = RandomForestClassifier(
        n_estimators= n_estimators,
        max_depth = max_depth,
        min_samples = min_samples,
        min_samples_leaf = min_samples_leaf,
        bootstrap = bootstrap,
        random_state = 42
    )

  elif classifier_name == 'GradientBoosting':
    n_estimators = trial.suggest_int('n_estimators', 50, 300)
    learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log = True)
    max_depth = trial.suggest_int('max_depth', 3, 20)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
    min_samples_leaf = trial.suggest_int('min_samples_split', 1, 10)

    model = GradientBoostingClassifier(
        n_estimators = n_estimators,
        learning_rate = learning_rate,
        min_samples_split = min_samples_split,
        max_depth = max_depth,
        min_samples_leaf = min_samples_leaf,
        random_state = 42
    )


    score = cross_val_score(model, X_train, y_train, cv = 3, scoring = 'accuracy').mean()
    return score

In [45]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials = 100)

[I 2026-04-24 14:25:50,329] A new study created in memory with name: no-name-daa600b2-2067-4486-98a5-e4257a9e0da1
/tmp/ipykernel_3969/427246939.py:31: RuntimeWarning:

Inconsistent parameter values for distribution with name "min_samples_split"! This might be a configuration mistake. Optuna allows to call the same distribution with the same name more than once in a trial. When the parameter values are inconsistent optuna only uses the values of the first call and ignores all following. Using these values: {'log': False, 'step': 1, 'low': 2, 'high': 10}

[I 2026-04-24 14:25:54,137] Trial 0 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 239, 'learning_rate': 0.03733545507033357, 'max_depth': 18, 'min_samples_split': 7}. Best is trial 0 with value: 0.7318435754189944.
[W 2026-04-24 14:25:54,140] Trial 1 failed with parameters: {'classifier': 'RandomForest', 'n_estimators': 225, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 7, 'bootstrap': True} because of the following error: TypeError("RandomForestClassifier.__init__() got an unexpected keyword argument 'min_samples'").
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_3969/427246939.py", line 17, in objective
    model = RandomForestClassifier(
            ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RandomForestClassifier.__init__() got an unexpected keyword argument 'min_samples'
[W 2026-04-24 14:25:54,143] Trial 1 failed with value None.

TypeError: RandomForestClassifier.__init__() got an unexpected keyword argument 'min_samples'