In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('http://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [6]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [22]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
463,11.600,18.36,73.88,412.7,0.08508,0.05855,0.03367,0.017770,0.1516,0.05859,...,12.77,24.02,82.68,495.1,0.1342,0.18080,0.18600,0.08288,0.3210,0.07863
508,16.300,15.70,104.70,819.8,0.09427,0.06712,0.05526,0.045630,0.1711,0.05657,...,17.32,17.76,109.80,928.2,0.1354,0.13610,0.19470,0.13570,0.2300,0.07230
110,9.777,16.99,62.50,290.2,0.10370,0.08404,0.04334,0.017780,0.1584,0.07065,...,11.05,21.47,71.68,367.0,0.1467,0.17650,0.13000,0.05334,0.2533,0.08468
390,10.260,12.22,65.75,321.6,0.09996,0.07542,0.01923,0.019680,0.1800,0.06569,...,11.38,15.65,73.23,394.5,0.1343,0.16500,0.08615,0.06696,0.2937,0.07722
41,10.950,21.35,71.90,371.1,0.12270,0.12180,0.10440,0.056690,0.1895,0.06870,...,12.84,35.34,87.22,514.0,0.1909,0.26980,0.40230,0.14240,0.2964,0.09606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554,12.880,28.92,82.50,514.3,0.08123,0.05824,0.06195,0.023430,0.1566,0.05708,...,13.89,35.74,88.84,595.7,0.1227,0.16200,0.24390,0.06493,0.2372,0.07242
302,20.090,23.86,134.70,1247.0,0.10800,0.18380,0.22830,0.128000,0.2249,0.07469,...,23.68,29.43,158.80,1696.0,0.1347,0.33910,0.49320,0.19230,0.3294,0.09469
239,17.460,39.28,113.40,920.6,0.09812,0.12980,0.14170,0.088110,0.1809,0.05966,...,22.51,44.87,141.20,1408.0,0.1365,0.37350,0.32410,0.20660,0.2853,0.08496
442,13.780,15.79,88.37,585.9,0.08817,0.06718,0.01055,0.009937,0.1405,0.05848,...,15.27,17.50,97.90,706.6,0.1072,0.10710,0.03517,0.03312,0.1859,0.06810
241,12.420,15.04,78.61,476.5,0.07926,0.03393,0.01053,0.011080,0.1546,0.05754,...,13.20,20.37,83.85,543.4,0.1037,0.07776,0.06243,0.04052,0.2901,0.06783

In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.values)
X_test = scaler.transform(X_test.values)

In [24]:
X_train

array([[-7.18671351e-01, -2.48561971e-01, -7.48399230e-01, ...,
        -4.81720034e-01,  4.88154137e-01, -2.92888178e-01],
       [ 6.41472909e-01, -8.54191898e-01,  5.46468523e-01, ...,
         3.24404706e-01, -9.54623918e-01, -6.27983351e-01],
       [-1.24623369e+00, -5.60484151e-01, -1.22651717e+00, ...,
        -9.32551629e-01, -5.85209317e-01,  2.73844594e-02],
       ...,
       [ 9.77168088e-01,  4.51451249e+00,  9.11989271e-01, ...,
         1.40646158e+00, -7.78587921e-02,  4.22069947e-02],
       [-8.77959286e-02, -8.33700660e-01, -1.39618122e-01, ...,
        -1.24114387e+00, -1.65381636e+00, -8.50321381e-01],
       [-4.81369587e-01, -1.00446098e+00, -5.49673582e-01, ...,
        -1.12820705e+00, -1.75621336e-03, -8.64614540e-01]])

In [25]:
y_train

463    B
508    B
110    B
390    B
41     M
      ..
554    B
302    M
239    M
442    B
241    B
Name: diagnosis, Length: 455, dtype: object

In [26]:
#Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [27]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0])

In [28]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [29]:
X_train_tensor

tensor([[-7.1867e-01, -2.4856e-01, -7.4840e-01,  ..., -4.8172e-01,
          4.8815e-01, -2.9289e-01],
        [ 6.4147e-01, -8.5419e-01,  5.4647e-01,  ...,  3.2440e-01,
         -9.5462e-01, -6.2798e-01],
        [-1.2462e+00, -5.6048e-01, -1.2265e+00,  ..., -9.3255e-01,
         -5.8521e-01,  2.7384e-02],
        ...,
        [ 9.7717e-01,  4.5145e+00,  9.1199e-01,  ...,  1.4065e+00,
         -7.7859e-02,  4.2207e-02],
        [-8.7796e-02, -8.3370e-01, -1.3962e-01,  ..., -1.2411e+00,
         -1.6538e+00, -8.5032e-01],
        [-4.8137e-01, -1.0045e+00, -5.4967e-01,  ..., -1.1282e+00,
         -1.7562e-03, -8.6461e-01]], dtype=torch.float64)

In [30]:
y_train_tensor

tensor([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0])

In [47]:
#defining Model

class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  #forward pass
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #Clamping predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #Calculate Loss
    # here we are using binary Cross Entropy Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [48]:
#Hyperparameters
learning_rate = 0.1
epochs = 25

In [52]:
#creating model
model = MySimpleNN(X_train_tensor)

#defining training loop
for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)

  #calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update
  # no need for grad in these parameters
  with torch.no_grad():
    model.weights -= model.weights.grad * learning_rate
    model.bias -= model.bias.grad * learning_rate

  #zero gradients
  # clearing grad for every epoch so that they dont cumulate
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.6211353197062475
Epoch: 2, Loss: 3.4891525075487637
Epoch: 3, Loss: 3.354257477470532
Epoch: 4, Loss: 3.2134163442903017
Epoch: 5, Loss: 3.069755422986006
Epoch: 6, Loss: 2.9224134665534773
Epoch: 7, Loss: 2.7643395942525513
Epoch: 8, Loss: 2.6083055689506924
Epoch: 9, Loss: 2.4474984200740226
Epoch: 10, Loss: 2.2876043024158306
Epoch: 11, Loss: 2.1272698277810784
Epoch: 12, Loss: 1.963469886963065
Epoch: 13, Loss: 1.803143487582714
Epoch: 14, Loss: 1.649826082036517
Epoch: 15, Loss: 1.5076094308673498
Epoch: 16, Loss: 1.3779261982222215
Epoch: 17, Loss: 1.262233041459353
Epoch: 18, Loss: 1.1618236561981368
Epoch: 19, Loss: 1.0775003301933705
Epoch: 20, Loss: 1.0091876627947773
Epoch: 21, Loss: 0.9556893201527553
Epoch: 22, Loss: 0.9147959223686978
Epoch: 23, Loss: 0.8837679344288031
Epoch: 24, Loss: 0.8599492336418794
Epoch: 25, Loss: 0.8411773975267527

In [54]:
model.weights

tensor([[-0.4121],
        [ 0.2555],
        [-0.1025],
        [-0.0628],
        [ 0.0908],
        [ 0.0257],
        [ 0.1259],
        [ 0.2161],
        [-0.1607],
        [-0.1218],
        [-0.2544],
        [ 0.6502],
        [ 0.0230],
        [ 0.2111],
        [ 0.2715],
        [ 0.3640],
        [-0.1191],
        [-0.0122],
        [ 0.3625],
        [-0.2453],
        [ 0.3296],
        [ 0.1186],
        [ 0.1881],
        [-0.3789],
        [-0.0253],
        [ 0.3746],
        [-0.3522],
        [ 0.2473],
        [ 0.0316],
        [-0.3671]], dtype=torch.float64, requires_grad=True)

In [55]:
model.bias

tensor([-0.1507], dtype=torch.float64, requires_grad=True)

In [58]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_train_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5298245549201965

In [ ]:
#using nn module to create a pipeline