In [ ]:
#using nn module

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model (nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

In [ ]:
#create a dataset
features = torch.rand(10, 5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.3450, -0.1351, -0.3250, -0.1046,  0.1727]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.4458], requires_grad=True)

In [ ]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [42]:
from torchinfo import summary
summary(model, input_size = (10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model_New_2                              [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [ ]:
#creating another model
#input 5, Hidden 3, Ouput 1
#input to hidden ReLU
#hidden to output Sigmoid

import torch
import torch.nn as nn

class Model_New (nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10, 5)

model = Model_New(features.shape[1])

model(features)

tensor([[0.4538],
        [0.4682],
        [0.4581],
        [0.4495],
        [0.4625],
        [0.4541],
        [0.4484],
        [0.4564],
        [0.4480],
        [0.4622]], grad_fn=<SigmoidBackward0>)

In [ ]:
features

tensor([[0.3586, 0.6560, 0.4477, 0.7497, 0.3264],
        [0.0656, 0.5854, 0.0186, 0.7524, 0.4183],
        [0.6724, 0.7813, 0.3304, 0.8848, 0.5955],
        [0.7321, 0.9233, 0.5863, 0.9403, 0.4136],
        [0.5433, 0.4871, 0.1720, 0.2938, 0.6134],
        [0.2154, 0.0793, 0.5260, 0.4203, 0.9591],
        [0.6746, 0.4817, 0.5111, 0.5436, 0.2505],
        [0.8457, 0.5512, 0.2126, 0.9343, 0.3096],
        [0.9671, 0.7604, 0.5474, 0.3431, 0.3266],
        [0.5727, 0.7934, 0.1368, 0.6888, 0.2845]])

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4059, -0.0437,  0.2907,  0.0130, -0.2269],
        [-0.0756,  0.0840, -0.3642, -0.0199,  0.0998],
        [-0.2514, -0.2512, -0.3714, -0.3388,  0.1141]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.0134,  0.3190,  0.3787]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.2639,  0.2425, -0.0518], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.2251], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size = (10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model_New                                [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [ ]:
#creating a model using Sequential pipeline

class Model_New_2(nn.Module):

  def __init__ (self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [ ]:
features = torch.rand(10, 5)
model = Model_New_2(features.shape[1])
model(features)

tensor([[0.5585],
        [0.5585],
        [0.5531],
        [0.5130],
        [0.5183],
        [0.5585],
        [0.5390],
        [0.5404],
        [0.5585],
        [0.5558]], grad_fn=<SigmoidBackward0>)

In [46]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [47]:
df = pd.read_csv('http://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [48]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [49]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [51]:
X_train

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
499       20.590         21.24  ...          0.2480                  0.08999
116        8.950         15.76  ...          0.1652                  0.07722
479       16.250         19.51  ...          0.3318                  0.09136
558       14.590         22.68  ...          0.2258                  0.08004
418       12.700         12.17  ...          0.2775                  0.09464
..           ...           ...  ...             ...                      ...
121       18.660         17.12  ...          0.2894                  0.08456
231       11.320         27.08  ...          0.2849                  0.07087
110        9.777         16.99  ...          0.2533                  0.08468
342       11.060         14.96  ...          0.3301                  0.09080
465       13.240         20.13  ...          0.2845                  0.12490

[455 rows x 30 columns]

In [52]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train.values)
X_test = scaler.transform(X_test.values)

In [53]:
X_train

array([[ 1.77698197,  0.47320961,  1.82860374, ...,  1.48875488,
        -0.70350211,  0.36401401],
       [-1.46861418, -0.82261576, -1.36604902, ..., -1.16062442,
        -2.11128357, -0.34191526],
       [ 0.5668542 ,  0.06412605,  0.69718106, ...,  0.97065132,
         0.72128154,  0.43974801],
       ...,
       [-1.23802071, -0.53176445, -1.21411511, ..., -0.93253622,
        -0.61339049,  0.07047568],
       [-0.88028017, -1.01178735, -0.85084762, ..., -0.10234424,
         0.69237782,  0.40879104],
       [-0.27242797,  0.21073403, -0.2293733 , ...,  0.32991969,
        -0.08292212,  2.29384885]])

In [54]:
y_train

499    M
116    B
479    M
558    B
418    B
      ..
121    M
231    B
110    B
342    B
465    B
Name: diagnosis, Length: 455, dtype: object

In [55]:
#Label Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [56]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [57]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [58]:
X_train_tensor

tensor([[ 1.7770,  0.4732,  1.8286,  ...,  1.4888, -0.7035,  0.3640],
        [-1.4686, -0.8226, -1.3660,  ..., -1.1606, -2.1113, -0.3419],
        [ 0.5669,  0.0641,  0.6972,  ...,  0.9707,  0.7213,  0.4397],
        ...,
        [-1.2380, -0.5318, -1.2141,  ..., -0.9325, -0.6134,  0.0705],
        [-0.8803, -1.0118, -0.8508,  ..., -0.1023,  0.6924,  0.4088],
        [-0.2724,  0.2107, -0.2294,  ...,  0.3299, -0.0829,  2.2938]],
       dtype=torch.float64)

In [59]:
y_train_tensor

tensor([1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
        0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [60]:
#now creating new model for this dataset

class MySimpleNN(nn.Module):

  def __init__ (self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out
"""
  def loss_function(self, y_pred, y):
    #Clamp predictions to avoid log(0) error
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #Calculating Loss
    # using binary Cross Entropy Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss
"""

In [71]:
#using built in loss function
#overwriting the above loss function
loss_function = nn.BCELoss()

In [72]:
# Hyperparameters
learning_rate = 0.1
epochs = 25

In [84]:
#creating model
model = MySimpleNN(X_train_tensor.shape[1])

#defining optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#defining loop
for epoch in range(epochs):

  #forward Pass
  y_pred = model(X_train_tensor.float())

  #loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1).float())

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #printing
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

""" # Replace this using optim of nn
  #parameter updation
  #dont need grad for this
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  #zero gradients
  #we dont want to cumulate the gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()
"""

Epoch: 1, Loss: 0.8670338988304138
Epoch: 2, Loss: 0.6095987558364868
Epoch: 3, Loss: 0.48348045349121094
Epoch: 4, Loss: 0.41245418787002563
Epoch: 5, Loss: 0.3660944104194641
Epoch: 6, Loss: 0.3330104649066925
Epoch: 7, Loss: 0.3079761266708374
Epoch: 8, Loss: 0.28822797536849976
Epoch: 9, Loss: 0.2721571922302246
Epoch: 10, Loss: 0.2587593197822571
Epoch: 11, Loss: 0.24737262725830078
Epoch: 12, Loss: 0.23754213750362396
Epoch: 13, Loss: 0.22894415259361267
Epoch: 14, Loss: 0.22134140133857727
Epoch: 15, Loss: 0.21455572545528412
Epoch: 16, Loss: 0.20845049619674683
Epoch: 17, Loss: 0.2029191255569458
Epoch: 18, Loss: 0.19787682592868805
Epoch: 19, Loss: 0.1932554543018341
Epoch: 20, Loss: 0.1889994591474533
Epoch: 21, Loss: 0.18506301939487457
Epoch: 22, Loss: 0.18140797317028046
Epoch: 23, Loss: 0.17800232768058777
Epoch: 24, Loss: 0.17481887340545654
Epoch: 25, Loss: 0.17183445394039154

' # Replace this using optim of nn\n  #parameter updation \n  #dont need grad for this  \n  with torch.no_grad():\n    model.linear.weight -= learning_rate * model.linear.weight.grad\n    model.linear.bias -= learning_rate * model.linear.bias.grad\n\n  #zero gradients\n  #we dont want to cumulate the gradients \n  model.linear.weight.grad.zero_()\n  model.linear.bias.grad.zero_()\n'

In [85]:
model.linear.weight

Parameter containing:
tensor([[ 0.2710,  0.1495,  0.2077,  0.0953,  0.1761,  0.1881,  0.3984,  0.4028,
         -0.0425,  0.0544,  0.2473, -0.0437,  0.2075,  0.1736, -0.1462,  0.0452,
         -0.0904, -0.0062, -0.0348, -0.1157,  0.2398,  0.2838,  0.4487,  0.1013,
          0.1777,  0.0610,  0.1993,  0.1111,  0.0334,  0.1209]],
       requires_grad=True)

In [86]:
model.linear.bias

Parameter containing:
tensor([-0.1891], requires_grad=True)